[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
auction = "81s1tEx4MPdVvqS6X84Mok5K4N5fMbRLzcsT5eo2K8J3"
rwa_nft = "dK6HkxoT5BHYdPJFomXNSSB1fBUoRjxGT7XxbQudFLH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*"]
